trigger:
- master
- az-devops

pool:
  vmImage: windows-2019

steps:
- powershell: |
    choco install docfx -y
    docfx docfx.json
    if ($lastexitcode -ne 0){
      throw ("Error generating document")
    }
  displayName: "docfx build"

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: _site
    artifactName: site

- task: AzureFileCopy@3
  inputs:
    sourcePath: _site
    azureSubscription: Visual Studio Enterprise
    destination: azureBlob
    storage: docfxazsite
    containerName: "$web"
